# config/packages/easy_admin.yaml

easy_admin:
    entities:
        Product:
            class: App\Entity\Product
            form:
                fields:
                    - { property: 'imageFile', type: 'vich_image' } # Champ pour le téléchargement d'images
            list:
                fields:
                    - 'price'
                    - { property: 'image', type: 'image', base_path: '%kernel.project_dir%/public/uploads/imqges' } # Chemin vers le répertoire des images
            show:
                fields:
                    - { property: 'image', type: 'image', base_path: '%kernel.project_dir%/public/uploads/imqges' } # Chemin vers le répertoire des images
