vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
        image:
            uri_prefix: /asset/uploads/images
            upload_destination: '%kernel.project_dir%/public/asset/uploads/images'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

    
        image_type:
            uri_prefix: /uploads/images/type_chambre
            upload_destination: '%kernel.project_dir%/public/uploads/images/type_chambre'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer